kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  namespace: test-rabbitmq
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        resources: {}
        image: hjgraca/rabbitmq_send_demo
        env:
        - name: RabbitMq__Host
          value: "$(RABBITMQ_SERVICE_HOST)"
        - name: RabbitMq__Username
          value: "guest"
        - name: RabbitMq__Password
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: password 
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: File
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        securityContext:
          privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler