kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  namespace: test-rabbitmq
  name: worker
  labels:
    app: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      name: worker
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        resources: {}
        image: hjgraca/rabbitmq_receive_demo
        env:
        - name: RabbitMq__Host
          value: "$(RABBITMQ_SERVICE_HOST)"
        - name: RabbitMq__Username
          value: "guest"
        - name: RabbitMq__Password
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: password 
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: File
        imagePullPolicy: Always
        securityContext:
          privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler